### ISSUE TITLE
Errors when running assertion-testing example

### ISSUE THREAD

**Issue by frunjik** [totaljs/examples#129]
Install
```
git clone https://github.com/totaljs/examples.git
cd examples
npm i total4
cd assertion-testing
node index.js
```

Browse
```
http://localhost:8000/test
```

Errors
```
TypeError: Cannot read properties of undefined (reading '0')
    at r.compare (\myprojects\examples\node_modules\total4\index.js:4446:24)
    at F.lookup (\myprojects\examples\node_modules\total4\index.js:11389:11)
    at global.ACTION (\myprojects\examples\node_modules\total4\index.js:20242:16)
    at Action.run (\myprojects\examples\node_modules\total4\test.js:119:20)
    at Test.t.next [as $next] (\myprojects\examples\node_modules\total4\test.js:156:11)
    at Action.t.$callback [as $evalroutecallback] (\myprojects\examples\node_modules\total4\test.js:40:5)
    at ControllerProto.json (\myprojects\examples\node_modules\total4\index.js:14766:8)
    at \myprojects\examples\node_modules\total4\index.js:14979:9
    at SchemaBuilderEntityProto.$process (\myprojects\examples\node_modules\total4\builders.js:2543:4)
    at SchemaOptions.<anonymous> (\myprojects\examples\node_modules\total4\builders.js:2633:8)
ERROR ======= 2024-03-27 02:41:41: TypeError ---> TypeError: Cannot read properties of undefined (reading '0') TypeError: Cannot read properties of undefined (reading '0')
    at r.compare (\myprojects\examples\node_modules\total4\index.js:4446:24)
    at F.lookup (\myprojects\examples\node_modules\total4\index.js:11389:11)
    at global.ACTION (\myprojects\examples\node_modules\total4\index.js:20242:16)
    at Action.run (\myprojects\examples\node_modules\total4\test.js:119:20)
    at Test.t.next [as $next] (\myprojects\examples\node_modules\total4\test.js:156:11)
    at Action.t.$callback [as $evalroutecallback] (\myprojects\examples\node_modules\total4\test.js:40:5)
    at ControllerProto.json (\myprojects\examples\node_modules\total4\index.js:14766:8)
    at \myprojects\examples\node_modules\total4\index.js:14979:9
    at SchemaBuilderEntityProto.$process (\myprojects\examples\node_modules\total4\builders.js:2543:4)
    at SchemaOptions.<anonymous> (\myprojects\examples\node_modules\total4\builders.js:2633:8)
```

**Comment by petersirka** [comment]
I fixed the problem in Total.js v4 `$ npm install total4@beta`.
