### ISSUE TITLE
0-learn new uncompleted example:)

### ISSUE THREAD

**Issue by kardesyazilim** [totaljs/examples#22]
======= 2015-05-02 18:00:29: framework.install('model', 'users') ---> SyntaxError: /Users/polemarch/Desktop/project/nodejs/examples/0-learn/models/users.js:22
User.setGet(function*(error, model, options, callback) {
                    ^
Unexpected token * /Users/polemarch/Desktop/project/nodejs/examples/0-learn/models/users.js:22
User.setGet(function*(error, model, options, callback) {
                    ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.Framework.install (/Users/polemarch/Desktop/project/nodejs/examples/0-learn/node_modules/total.js/index.js:1:29139)
    at /Users/polemarch/Desktop/project/nodejs/examples/0-learn/node_modules/total.js/index.js:1:24484
    at Array.forEach (native)

**Comment by petersirka** [comment]
Hi @kardesyazilim,
the example needs enable harmony (only node.js v0.11.+), so try to run example via:

```bash
node --harmony index.js
```

Thanks :+1:

**Comment by petersirka** [comment]
More info here:
http://docs.totaljs.com/v1.8.x/en.html#pages~Synchronous%20programming

**Comment by kardesyazilim** [comment]
thanks bro
