### ISSUE TITLE
ReferenceError: MAIN is not defined

### ISSUE THREAD

**Issue by Damdias** [totaljs/examples#80]
when I download the source and try run after install total.js its getting below error

ReferenceError: MAIN is not defined
    at ChildProcess.<anonymous> (E:\Projects\Nodejs\totaljs\examples\workers\definitions\worker.js:7:3)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by petersirka** [comment]
Hi @Damdias, sorry for troubles. I'm preparing examples for a new version of Total.js which will be published in these days (maybe next week).

You can use a stable beta version `$ npm install total.js@beta` and everything will work correcly.

**Comment by petersirka** [comment]
BTW: here is the updated documentation: <https://docs.totaljs.com/v3.x.x/en.html#pages~Getting%20started>
